### ISSUE TITLE
Trying to render a multiline prerotate command, error parsing a flow sequence

### ISSUE THREAD

**Issue by daks** [saltstack-formulas/logrotate-formula#31]
Hello,

In Debian, default Nginx logrotate looks like:

```
/var/log/nginx/*.log {
        daily
        missingok
        rotate 14
        compress
        delaycompress
        notifempty
        create 0640 www-data adm
        sharedscripts
        prerotate
                if [ -d /etc/logrotate.d/httpd-prerotate ]; then \
                        run-parts /etc/logrotate.d/httpd-prerotate; \
                fi \
        endscript
        postrotate
                invoke-rc.d nginx rotate >/dev/null 2>&1
        endscript
}
```

I'm trying to generate this config with the formula but can't find the way to do it for the multiline prerotate part.

My naive implementation is:
```
logrotate:
  jobs:
    nginx:
      path:
        - /var/log/nginx/*.log
      config:
        # ...
        - prerotate
        -   if [ -d /etc/logrotate.d/httpd-prerotate ]; then \
        -     run-parts /etc/logrotate.d/httpd-prerotate; \
        -   fi \
        - endscript
```

But I got an error when running highstate

```
[CRITICAL] Rendering SLS 'base:logrotate.jobs' failed: while parsing a flow sequence
  in "<unicode string>", line 82, column 13:
          data: [u'weekly', u'missingok', u'comp ... 
                ^
expected ',' or ']', but got '['
  in "<unicode string>", line 82, column 151:
     ... redscripts', u'prerotate', u'if [ -d /etc/logrotate.d/httpd-prer ... 
                                         ^
local:
    Data failed to compile:
----------
    Rendering SLS 'base:logrotate.jobs' failed: while parsing a flow sequence
  in "<unicode string>", line 82, column 13:
          data: [u'weekly', u'missingok', u'comp ... 
                ^
expected ',' or ']', but got '['
  in "<unicode string>", line 82, column 151:
     ... redscripts', u'prerotate', u'if [ -d /etc/logrotate.d/httpd-prer ... 
                                         ^
```

I tried to single/double quote the multiple lines: no success.

Is this a bug or do I need to do something to 'encode' my multiline prerotate script?

**Comment by daks** [comment]
The problem is the inclusion of `[` like said in the error message

```
expected ',' or ']', but got '['
```

I tried to escape it with `\`, no success.

**Comment by n-rodriguez** [comment]
Did you try this :

```yml
logrotate:
  jobs:
    nginx:
      path:
        - /var/log/nginx/*.log
      config:
        # ...
        - prerotate
        -   "if [ -d /etc/logrotate.d/httpd-prerotate ]; then \"
        -   "  run-parts /etc/logrotate.d/httpd-prerotate; \"
        -   "fi \"
        - endscript
```
