### ISSUE TITLE
Bug: when job name is a path, no path in logrotate file

### ISSUE THREAD

**Issue by daks** [saltstack-formulas/logrotate-formula#33]
Hello,

while writing tests for jobs (see #32) I found that a job configured like this
```
logrotate:
  jobs:
    /tmp/var/log/mysql/error:
      config:
        - weekly
        - missingok
        - rotate 52
        - compress
        - delaycompress
        - notifempty
        - create 640 root adm
        - sharedscripts
```

generates the following logrotate file
```
# vim: sw=2 sts=2 ts=2 sw et
#
# This file is managed by salt. Do not edit by hand.
#

{
  weekly
  missingok
  rotate 52
  compress
  delaycompress
  notifempty
  create 640 root adm
  sharedscripts
}
```

This file is missing the path /tmp/var/log/mysql/error so the generated file is useless, even if logrotate do work.

_(test is commented out at the moment while this bug exists https://github.com/saltstack-formulas/logrotate-formula/pull/32/files#diff-c5d9a182ed31382e14c9db96116cfd04R10_
