### ISSUE TITLE
[BUG] wtmp and btmp are duplicated - debian12

### ISSUE THREAD

**Issue by FabRons** [saltstack-formulas/logrotate-formula#70]
### Formula commit hash / release tag

Release tag used: `0.14.0`

### Versions reports (master & minion)

- Master:  `3006.7`
- Minion: `3006.8`

### Pillar / config used

Log rotate global config:
```
logrotate:
  default_config:
    weekly: true
    rotate: 4
    create: true
    compress: false
    dateext: true
    dateformat: "-%Y%m%d-%s"
  jobs:
    syslog-local:
      path:
        - /var/log/local.log
        - /var/log/auditd.log
      config:
        - rotate 7
        - daily
        - missingok
        - notifempty
        - compress
        - delaycompress
        - sharedscripts
        - postrotate
        - "  invoke-rc.d rsyslog rotate > /dev/null"
        - endscript
```
---

### Describe the bug

Our default config add `wtmp` & `btmp` in  `logrotate.conf`:
```
              diff:
                  --- 
                  +++ 
                  @@ -22,18 +22,18 @@
                   include /etc/logrotate.d
                   
                   # no packages own wtmp and btmp -- we'll rotate them here
                  +/var/log/wtmp {
                  +    monthly
                  +    create 0664 root utmp
                  +    minsize 1M
                  +    rotate 1
                  +}
                   
                  +/var/log/btmp {
                  +    missingok
                  +    monthly
                  +    create 0600 root utmp
                  +    rotate 1
                  +}
```
However, wtmp & btmp already configured here:
```
 # ls /etc/logrotate.d/|grep tmp
btmp
wtmp
```
Cause crash of service:
```
# systemctl status logrotate
× logrotate.service - Rotate log files
     Loaded: loaded (/lib/systemd/system/logrotate.service; static)
     Active: failed (Result: exit-code) since Fri 2024-07-12 00:00:00 CEST; 10h ago
TriggeredBy: ● logrotate.timer
       Docs: man:logrotate(8)
             man:logrotate.conf(5)
   Main PID: 1065653 (code=exited, status=1/FAILURE)
        CPU: 49ms

systemd[1]: Starting logrotate.service - Rotate log files...
logrotate[1065653]: error: /etc/logrotate.conf:25 duplicate log entry for /var/log/wtmp
logrotate[1065653]: error: /etc/logrotate.conf:32 duplicate log entry for /var/log/btmp
systemd[1]: logrotate.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: logrotate.service: Failed with result 'exit-code'.
systemd[1]: Failed to start logrotate.service - Rotate log files.
```

Only on deb12, all previous version didn't have any problem.

### Steps to reproduce the bug

Use logrotate formula basic config and apply with debian 12 OS

### Expected behaviour
Salt didn't add wtmp & btmp in logrotate.conf, so didn't make crash logrotate serrvice

### Attempts to fix the bug

Quick fix:
```
# rm /etc/logrotate.d/*tmp 
```

Best regards,

Fabien
